[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
coinsec = "ExMya4ZkN2dVoXJLyMNYxSjTmG4M8dUKPnokQhVDH39V"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
